# Generated by Django 4.2.7 on 2023-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, help_text='product price')),
                ('description', models.TextField(blank=True, help_text='product describtion')),
            ],
        ),
    ]
